# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Ariel Silva
  pt: Ariel Silva
email: ariel.abreu.silva@gmail.com
description:
  en: Nodejs Developer writing about TDD, JS and code-related psychology.
  pt: Desenvolvedor Nodejs escrevendo sobre TDD, JS e psicologia aplicada à programação.
index:
  en: index.html
  pt: inicio.html
feed:
  en: 
  pt: 
# baseurl: "/jekyll-multilingual" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  SilvaAriel
linkedin_username: ariel-abreu-silva

# Build settings
markdown: kramdown
